import type { CountryProfile } from "@/types/smart-map";

/** Launch country first; profiles for all 54 African countries for expansion. */
export const COUNTRIES: CountryProfile[] = [
  {
    code: "GH",
    name: "Ghana",
    flag: "🇬🇭",
    capital: "Accra",
    languages: ["English", "Twi", "Ga", "Ewe", "Dagbani"],
    emergency: { police: "191", fire: "192", ambulance: "193", general: "112" },
    center: { lat: 5.6037, lng: -0.187 },
    zoom: 12,
  },
  {
    code: "NG",
    name: "Nigeria",
    flag: "🇳🇬",
    capital: "Abuja",
    languages: ["English", "Hausa", "Yoruba", "Igbo"],
    emergency: { police: "112", fire: "112", ambulance: "112", general: "112" },
    center: { lat: 9.0765, lng: 7.3986 },
    zoom: 11,
  },
  {
    code: "KE",
    name: "Kenya",
    flag: "🇰🇪",
    capital: "Nairobi",
    languages: ["English", "Swahili"],
    emergency: { police: "999", fire: "999", ambulance: "999", general: "112" },
    center: { lat: -1.2921, lng: 36.8219 },
    zoom: 12,
  },
  {
    code: "ZA",
    name: "South Africa",
    flag: "🇿🇦",
    capital: "Pretoria",
    languages: ["English", "Zulu", "Xhosa", "Afrikaans"],
    emergency: { police: "10111", fire: "10177", ambulance: "10177", general: "112" },
    center: { lat: -25.7479, lng: 28.2293 },
    zoom: 11,
  },
  {
    code: "EG",
    name: "Egypt",
    flag: "🇪🇬",
    capital: "Cairo",
    languages: ["Arabic", "English"],
    emergency: { police: "122", fire: "180", ambulance: "123", general: "112" },
    center: { lat: 30.0444, lng: 31.2357 },
    zoom: 11,
  },
  {
    code: "ET",
    name: "Ethiopia",
    flag: "🇪🇹",
    capital: "Addis Ababa",
    languages: ["Amharic", "English", "Oromo"],
    emergency: { police: "991", fire: "939", ambulance: "907", general: "911" },
    center: { lat: 9.03, lng: 38.74 },
    zoom: 11,
  },
  {
    code: "TZ",
    name: "Tanzania",
    flag: "🇹🇿",
    capital: "Dodoma",
    languages: ["Swahili", "English"],
    emergency: { police: "112", fire: "114", ambulance: "115", general: "112" },
    center: { lat: -6.163, lng: 35.7516 },
    zoom: 11,
  },
  {
    code: "UG",
    name: "Uganda",
    flag: "🇺🇬",
    capital: "Kampala",
    languages: ["English", "Luganda"],
    emergency: { police: "999", fire: "999", ambulance: "911", general: "112" },
    center: { lat: 0.3476, lng: 32.5825 },
    zoom: 12,
  },
  {
    code: "RW",
    name: "Rwanda",
    flag: "🇷🇼",
    capital: "Kigali",
    languages: ["Kinyarwanda", "English", "French"],
    emergency: { police: "112", fire: "112", ambulance: "912", general: "112" },
    center: { lat: -1.9441, lng: 30.0619 },
    zoom: 12,
  },
  {
    code: "CI",
    name: "Côte d'Ivoire",
    flag: "🇨🇮",
    capital: "Yamoussoukro",
    languages: ["French"],
    emergency: { police: "110", fire: "180", ambulance: "185", general: "112" },
    center: { lat: 6.8276, lng: -5.2893 },
    zoom: 11,
  },
  {
    code: "SN",
    name: "Senegal",
    flag: "🇸🇳",
    capital: "Dakar",
    languages: ["French", "Wolof"],
    emergency: { police: "17", fire: "18", ambulance: "15", general: "112" },
    center: { lat: 14.7167, lng: -17.4677 },
    zoom: 12,
  },
  {
    code: "MA",
    name: "Morocco",
    flag: "🇲🇦",
    capital: "Rabat",
    languages: ["Arabic", "French", "Berber"],
    emergency: { police: "19", fire: "15", ambulance: "15", general: "112" },
    center: { lat: 34.0209, lng: -6.8416 },
    zoom: 11,
  },
  {
    code: "GH-EXPAND",
    name: "Africa Network",
    flag: "🌍",
    capital: "Pan-African",
    languages: ["English", "French", "Arabic", "Portuguese", "Swahili"],
    emergency: { police: "112", fire: "112", ambulance: "112", general: "112" },
    center: { lat: 1.5, lng: 17.5 },
    zoom: 3,
  },
];

export const LAUNCH_COUNTRY = COUNTRIES[0];

export function getCountry(code: string): CountryProfile {
  return COUNTRIES.find((c) => c.code === code) ?? LAUNCH_COUNTRY;
}

/** Remaining African countries for country management (codes + names). */
export const AFRICA_COUNTRY_CODES: { code: string; name: string; flag: string }[] = [
  { code: "DZ", name: "Algeria", flag: "🇩🇿" },
  { code: "AO", name: "Angola", flag: "🇦🇴" },
  { code: "BJ", name: "Benin", flag: "🇧🇯" },
  { code: "BW", name: "Botswana", flag: "🇧🇼" },
  { code: "BF", name: "Burkina Faso", flag: "🇧🇫" },
  { code: "BI", name: "Burundi", flag: "🇧🇮" },
  { code: "CV", name: "Cabo Verde", flag: "🇨🇻" },
  { code: "CM", name: "Cameroon", flag: "🇨🇲" },
  { code: "CF", name: "Central African Republic", flag: "🇨🇫" },
  { code: "TD", name: "Chad", flag: "🇹🇩" },
  { code: "KM", name: "Comoros", flag: "🇰🇲" },
  { code: "CG", name: "Congo", flag: "🇨🇬" },
  { code: "CD", name: "DR Congo", flag: "🇨🇩" },
  { code: "DJ", name: "Djibouti", flag: "🇩🇯" },
  { code: "GQ", name: "Equatorial Guinea", flag: "🇬🇶" },
  { code: "ER", name: "Eritrea", flag: "🇪🇷" },
  { code: "SZ", name: "Eswatini", flag: "🇸🇿" },
  { code: "GA", name: "Gabon", flag: "🇬🇦" },
  { code: "GM", name: "Gambia", flag: "🇬🇲" },
  { code: "GN", name: "Guinea", flag: "🇬🇳" },
  { code: "GW", name: "Guinea-Bissau", flag: "🇬🇼" },
  { code: "LS", name: "Lesotho", flag: "🇱🇸" },
  { code: "LR", name: "Liberia", flag: "🇱🇷" },
  { code: "LY", name: "Libya", flag: "🇱🇾" },
  { code: "MG", name: "Madagascar", flag: "🇲🇬" },
  { code: "MW", name: "Malawi", flag: "🇲🇼" },
  { code: "ML", name: "Mali", flag: "🇲🇱" },
  { code: "MR", name: "Mauritania", flag: "🇲🇷" },
  { code: "MU", name: "Mauritius", flag: "🇲🇺" },
  { code: "MZ", name: "Mozambique", flag: "🇲🇿" },
  { code: "NA", name: "Namibia", flag: "🇳🇦" },
  { code: "NE", name: "Niger", flag: "🇳🇪" },
  { code: "ST", name: "São Tomé and Príncipe", flag: "🇸🇹" },
  { code: "SC", name: "Seychelles", flag: "🇸🇨" },
  { code: "SL", name: "Sierra Leone", flag: "🇸🇱" },
  { code: "SO", name: "Somalia", flag: "🇸🇴" },
  { code: "SS", name: "South Sudan", flag: "🇸🇸" },
  { code: "SD", name: "Sudan", flag: "🇸🇩" },
  { code: "TG", name: "Togo", flag: "🇹🇬" },
  { code: "TN", name: "Tunisia", flag: "🇹🇳" },
  { code: "ZM", name: "Zambia", flag: "🇿🇲" },
  { code: "ZW", name: "Zimbabwe", flag: "🇿🇼" },
];
