import type { Place } from "@/types/smart-map";

export type GovernmentServiceKind =
  | "passport"
  | "immigration"
  | "dvla"
  | "court"
  | "assembly"
  | "ecg"
  | "ghana_water"
  | "ambulance"
  | "police_command"
  | "fire_command";

export interface GovernmentService extends Place {
  serviceKind: GovernmentServiceKind;
  agency: string;
}

export const GOVERNMENT_SERVICES: GovernmentService[] = [
  {
    id: "gh-passport-accra",
    name: "Ghana Passport Office — Accra",
    serviceKind: "passport",
    agency: "Ministry of Foreign Affairs",
    category: "passport",
    coordinates: { lat: 5.582, lng: -0.2 },
    address: "Ministries, Accra",
    city: "Accra",
    region: "Greater Accra",
    country: "Ghana",
    countryCode: "GH",
    phone: "+233-302-684-000",
    hours: "8am – 4pm · Mon–Fri",
    verified: "government",
  },
  {
    id: "gh-immigration-accra",
    name: "Ghana Immigration Service — HQ",
    serviceKind: "immigration",
    agency: "Ghana Immigration Service",
    category: "government",
    coordinates: { lat: 5.578, lng: -0.198 },
    address: "Independence Avenue, Accra",
    city: "Accra",
    region: "Greater Accra",
    country: "Ghana",
    countryCode: "GH",
    verified: "government",
  },
  {
    id: "gh-dvla-accra",
    name: "DVLA Accra",
    serviceKind: "dvla",
    agency: "Driver and Vehicle Licensing Authority",
    category: "dvla",
    coordinates: { lat: 5.612, lng: -0.2 },
    address: "Accra",
    city: "Accra",
    region: "Greater Accra",
    country: "Ghana",
    countryCode: "GH",
    verified: "government",
  },
  {
    id: "gh-court-supreme",
    name: "Supreme Court of Ghana",
    serviceKind: "court",
    agency: "Judicial Service",
    category: "court",
    coordinates: { lat: 5.55, lng: -0.205 },
    address: "High Court Area, Accra",
    city: "Accra",
    region: "Greater Accra",
    country: "Ghana",
    countryCode: "GH",
    verified: "government",
  },
  {
    id: "gh-assembly-ama",
    name: "Accra Metropolitan Assembly",
    serviceKind: "assembly",
    agency: "AMA",
    category: "government",
    coordinates: { lat: 5.55, lng: -0.2 },
    address: "Accra",
    city: "Accra",
    region: "Greater Accra",
    country: "Ghana",
    countryCode: "GH",
    verified: "government",
  },
  {
    id: "gh-ecg-accra",
    name: "ECG Customer Service — Accra",
    serviceKind: "ecg",
    agency: "Electricity Company of Ghana",
    category: "government",
    coordinates: { lat: 5.57, lng: -0.2 },
    address: "Electro-Volta House area, Accra",
    city: "Accra",
    region: "Greater Accra",
    country: "Ghana",
    countryCode: "GH",
    verified: "government",
  },
  {
    id: "gh-water-gwcl",
    name: "Ghana Water — Accra East",
    serviceKind: "ghana_water",
    agency: "Ghana Water Company Limited",
    category: "government",
    coordinates: { lat: 5.59, lng: -0.17 },
    address: "Accra",
    city: "Accra",
    region: "Greater Accra",
    country: "Ghana",
    countryCode: "GH",
    verified: "government",
  },
  {
    id: "gh-ambulance-nas",
    name: "National Ambulance Service — Accra",
    serviceKind: "ambulance",
    agency: "National Ambulance Service",
    category: "ambulance",
    coordinates: { lat: 5.59, lng: -0.186 },
    address: "Ridge, Accra",
    city: "Accra",
    region: "Greater Accra",
    country: "Ghana",
    countryCode: "GH",
    phone: "193",
    verified: "government",
  },
  {
    id: "gh-police-regional",
    name: "Greater Accra Regional Police Command",
    serviceKind: "police_command",
    agency: "Ghana Police Service",
    category: "police",
    coordinates: { lat: 5.575, lng: -0.195 },
    address: "Accra",
    city: "Accra",
    region: "Greater Accra",
    country: "Ghana",
    countryCode: "GH",
    phone: "191",
    verified: "police",
  },
  {
    id: "gh-fire-regional",
    name: "GNFS Greater Accra Regional Command",
    serviceKind: "fire_command",
    agency: "Ghana National Fire Service",
    category: "fire",
    coordinates: { lat: 5.568, lng: -0.24 },
    address: "Kaneshie, Accra",
    city: "Accra",
    region: "Greater Accra",
    country: "Ghana",
    countryCode: "GH",
    phone: "192",
    verified: "government",
  },
];
