import type { Place } from "@/types/smart-map";

export const ASHANTI_SHOWCASE: Place[] = [
  { id: "gh-bedomase", name: "Bedomase", category: "attraction", coordinates: { lat: 6.958492, lng: -1.500275 }, address: "Bedomase, Sekyere South", city: "Bedomase", region: "Ashanti", country: "Ghana", countryCode: "GH", rating: 4.6, reviewCount: 42 },
  { id: "gh-agona-ashanti", name: "Agona", category: "market", coordinates: { lat: 6.994, lng: -1.573 }, address: "Agona, Ashanti Region", city: "Agona", region: "Ashanti", country: "Ghana", countryCode: "GH", rating: 4.4, reviewCount: 88 },
  { id: "gh-agona-bipoa", name: "Agona-Bipoa", category: "market", coordinates: { lat: 6.978, lng: -1.548 }, address: "Agona-Bipoa, Ashanti", city: "Agona-Bipoa", region: "Ashanti", country: "Ghana", countryCode: "GH", rating: 4.3, reviewCount: 31 },
  { id: "gh-jamasi", name: "Jamasi", category: "school", coordinates: { lat: 6.932, lng: -1.478 }, address: "Jamasi, Ashanti Region", city: "Jamasi", region: "Ashanti", country: "Ghana", countryCode: "GH", rating: 4.5, reviewCount: 56 },
  { id: "gh-sda-college-agona", name: "SDA College of Education, Agona", category: "university", coordinates: { lat: 6.991, lng: -1.565 }, address: "Ofinso - Juansa Rd, Agona", city: "Agona", region: "Ashanti", country: "Ghana", countryCode: "GH", rating: 4.7, reviewCount: 124 },
];

/** Curated Accra / Greater Accra places for launch demo data. */
export const PLACES: Place[] = [
  ...ASHANTI_SHOWCASE,
  {
    id: "gh-police-accra-central",
    name: "Accra Central Police Station",
    category: "police",
    coordinates: { lat: 5.715, lng: -0.216 },
    address: "High Street, Accra",
    city: "Accra",
    region: "Greater Accra",
    country: "Ghana",
    countryCode: "GH",
    phone: "+233-302-666-666",
    hours: "24 hours",
    rating: 4.1,
    reviewCount: 128,
    verified: "police",
    accessibility: true,
    description: "Primary central police station serving Accra CBD.",
  },
  {
    id: "gh-fire-kaneshie",
    name: "Kaneshie Fire Service",
    category: "fire",
    coordinates: { lat: 5.568, lng: -0.24 },
    address: "Kaneshie, Accra",
    city: "Accra",
    region: "Greater Accra",
    country: "Ghana",
    countryCode: "GH",
    phone: "192",
    hours: "24 hours",
    verified: "government",
    rating: 4.3,
    reviewCount: 64,
  },
  {
    id: "gh-ambulance-nas",
    name: "National Ambulance Service — Accra",
    category: "ambulance",
    coordinates: { lat: 5.59, lng: -0.186 },
    address: "Ridge, Accra",
    city: "Accra",
    region: "Greater Accra",
    country: "Ghana",
    countryCode: "GH",
    phone: "193",
    hours: "24 hours",
    verified: "government",
    rating: 4.5,
    reviewCount: 210,
  },
  {
    id: "gh-hospital-korle-bu",
    name: "Korle Bu Teaching Hospital",
    category: "hospital",
    coordinates: { lat: 5.537, lng: -0.226 },
    address: "Guggisberg Ave, Accra",
    city: "Accra",
    region: "Greater Accra",
    country: "Ghana",
    countryCode: "GH",
    phone: "+233-302-665-401",
    website: "https://kbth.gov.gh",
    hours: "24 hours · Emergency",
    rating: 4.2,
    reviewCount: 1840,
    verified: "hospital",
    accessibility: true,
    parking: true,
    popularTimes: "Busy 8am–2pm",
    description: "Ghana's largest referral hospital with emergency and specialist care.",
  },
  {
    id: "gh-clinic-ridge",
    name: "Ridge Clinic",
    category: "clinic",
    coordinates: { lat: 5.56, lng: -0.2 },
    address: "Ridge, Accra",
    city: "Accra",
    region: "Greater Accra",
    country: "Ghana",
    countryCode: "GH",
    phone: "+233-302-220-110",
    hours: "8am – 8pm",
    rating: 4.0,
    reviewCount: 96,
    verified: "hospital",
    description: "Community clinic with outpatient and urgent care.",
  },
  {
    id: "gh-shelter-nadmo-accra",
    name: "NADMO Safe Shelter — Accra",
    category: "shelter",
    coordinates: { lat: 5.58, lng: -0.21 },
    address: "Ministries, Accra",
    city: "Accra",
    region: "Greater Accra",
    country: "Ghana",
    countryCode: "GH",
    phone: "+233-302-684-263",
    hours: "24 hours",
    verified: "government",
    description: "Designated emergency shelter coordinated by NADMO.",
  },
  {
    id: "gh-disaster-nadmo-hq",
    name: "NADMO Disaster Coordination Center",
    category: "disaster_center",
    coordinates: { lat: 5.57, lng: -0.205 },
    address: "Accra",
    city: "Accra",
    region: "Greater Accra",
    country: "Ghana",
    countryCode: "GH",
    phone: "+233-302-684-263",
    hours: "24 hours",
    verified: "government",
    description: "National disaster management operations center.",
  },
  {
    id: "gh-hospital-37",
    name: "37 Military Hospital",
    category: "hospital",
    coordinates: { lat: 5.587, lng: -0.18 },
    address: "Liberation Road, Accra",
    city: "Accra",
    region: "Greater Accra",
    country: "Ghana",
    countryCode: "GH",
    phone: "+233-302-777-751",
    hours: "24 hours",
    rating: 4.4,
    reviewCount: 960,
    verified: "hospital",
    accessibility: true,
    parking: true,
  },
  {
    id: "gh-pharmacy-erNest",
    name: "Ernest Chemists — Osu",
    category: "pharmacy",
    coordinates: { lat: 5.558, lng: -0.175 },
    address: "Oxford Street, Osu",
    city: "Accra",
    region: "Greater Accra",
    country: "Ghana",
    countryCode: "GH",
    phone: "+233-302-775-111",
    hours: "8am – 9pm",
    rating: 4.6,
    reviewCount: 420,
    verified: "business",
  },
  {
    id: "gh-uni-legon",
    name: "University of Ghana, Legon",
    category: "university",
    coordinates: { lat: 5.65, lng: -0.187 },
    address: "Legon, Accra",
    city: "Accra",
    region: "Greater Accra",
    country: "Ghana",
    countryCode: "GH",
    website: "https://www.ug.edu.gh",
    hours: "Campus open daily",
    rating: 4.5,
    reviewCount: 3200,
    verified: "school",
    parking: true,
    accessibility: true,
  },
  {
    id: "gh-school-presec",
    name: "PRESEC Legon",
    category: "school",
    coordinates: { lat: 5.655, lng: -0.182 },
    address: "Legon, Accra",
    city: "Accra",
    region: "Greater Accra",
    country: "Ghana",
    countryCode: "GH",
    verified: "school",
    rating: 4.7,
    reviewCount: 540,
  },
  {
    id: "gh-hotel-labadi",
    name: "Labadi Beach Hotel",
    category: "hotel",
    coordinates: { lat: 5.56, lng: -0.148 },
    address: "La, Accra",
    city: "Accra",
    region: "Greater Accra",
    country: "Ghana",
    countryCode: "GH",
    phone: "+233-302-772-501",
    website: "https://www.labadibeachhotel.com",
    hours: "Check-in 2pm",
    rating: 4.4,
    reviewCount: 2100,
    verified: "business",
    parking: true,
    accessibility: true,
  },
  {
    id: "gh-restaurant-azmera",
    name: "Buka Restaurant",
    category: "restaurant",
    coordinates: { lat: 5.57, lng: -0.182 },
    address: "10th Lane, Osu",
    city: "Accra",
    region: "Greater Accra",
    country: "Ghana",
    countryCode: "GH",
    hours: "11am – 10pm",
    rating: 4.5,
    reviewCount: 890,
    verified: "business",
    popularTimes: "Peak 7–9pm",
  },
  {
    id: "gh-bank-gcb-ridge",
    name: "GCB Bank — Ridge",
    category: "bank",
    coordinates: { lat: 5.575, lng: -0.19 },
    address: "Ridge, Accra",
    city: "Accra",
    region: "Greater Accra",
    country: "Ghana",
    countryCode: "GH",
    phone: "+233-302-664-910",
    hours: "8:30am – 4pm",
    rating: 4.0,
    reviewCount: 310,
    verified: "business",
  },
  {
    id: "gh-atm-stanbic-airport",
    name: "Stanbic ATM — Airport",
    category: "atm",
    coordinates: { lat: 5.605, lng: -0.168 },
    address: "Airport City, Accra",
    city: "Accra",
    region: "Greater Accra",
    country: "Ghana",
    countryCode: "GH",
    hours: "24 hours",
    rating: 4.2,
    reviewCount: 88,
    verified: "business",
  },
  {
    id: "gh-fuel-shell-spintex",
    name: "Shell — Spintex",
    category: "fuel",
    coordinates: { lat: 5.635, lng: -0.12 },
    address: "Spintex Road, Accra",
    city: "Accra",
    region: "Greater Accra",
    country: "Ghana",
    countryCode: "GH",
    hours: "24 hours",
    rating: 4.3,
    reviewCount: 240,
    verified: "business",
  },
  {
    id: "gh-market-makola",
    name: "Makola Market",
    category: "market",
    coordinates: { lat: 5.548, lng: -0.21 },
    address: "Makola, Accra",
    city: "Accra",
    region: "Greater Accra",
    country: "Ghana",
    countryCode: "GH",
    hours: "6am – 6pm",
    rating: 4.1,
    reviewCount: 1500,
    description: "Historic central market for groceries, fabrics, and household goods.",
  },
  {
    id: "gh-bus-circle",
    name: "Circle Bus Terminal",
    category: "bus_station",
    coordinates: { lat: 5.574, lng: -0.215 },
    address: "Kwame Nkrumah Circle, Accra",
    city: "Accra",
    region: "Greater Accra",
    country: "Ghana",
    countryCode: "GH",
    hours: "5am – 10pm",
    rating: 3.8,
    reviewCount: 620,
  },
  {
    id: "gh-airport-kotoka",
    name: "Kotoka International Airport",
    category: "airport",
    coordinates: { lat: 5.6052, lng: -0.1668 },
    address: "Airport Road, Accra",
    city: "Accra",
    region: "Greater Accra",
    country: "Ghana",
    countryCode: "GH",
    phone: "+233-302-776-171",
    website: "https://www.gacl.com.gh",
    hours: "24 hours",
    rating: 4.0,
    reviewCount: 5400,
    verified: "government",
    accessibility: true,
    parking: true,
  },
  {
    id: "gh-church-holy-spirit",
    name: "Holy Spirit Cathedral",
    category: "church",
    coordinates: { lat: 5.56, lng: -0.19 },
    address: "Adabraka, Accra",
    city: "Accra",
    region: "Greater Accra",
    country: "Ghana",
    countryCode: "GH",
    rating: 4.6,
    reviewCount: 180,
  },
  {
    id: "gh-mosque-nima",
    name: "Nima Central Mosque",
    category: "mosque",
    coordinates: { lat: 5.586, lng: -0.195 },
    address: "Nima, Accra",
    city: "Accra",
    region: "Greater Accra",
    country: "Ghana",
    countryCode: "GH",
    rating: 4.7,
    reviewCount: 260,
  },
  {
    id: "gh-gov-jubilee",
    name: "Jubilee House",
    category: "government",
    coordinates: { lat: 5.58, lng: -0.178 },
    address: "Flagstaff House, Accra",
    city: "Accra",
    region: "Greater Accra",
    country: "Ghana",
    countryCode: "GH",
    verified: "government",
    rating: 4.2,
    reviewCount: 90,
  },
  {
    id: "gh-passport-accra",
    name: "Ghana Passport Office — Accra",
    category: "passport",
    coordinates: { lat: 5.582, lng: -0.2 },
    address: "Ministries, Accra",
    city: "Accra",
    region: "Greater Accra",
    country: "Ghana",
    countryCode: "GH",
    phone: "+233-302-684-000",
    hours: "8am – 4pm · Mon–Fri",
    verified: "government",
    rating: 3.6,
    reviewCount: 780,
    popularTimes: "Very busy mornings",
  },
  {
    id: "gh-dvla-accra",
    name: "DVLA Accra",
    category: "dvla",
    coordinates: { lat: 5.612, lng: -0.2 },
    address: "Acheampong High Street area",
    city: "Accra",
    region: "Greater Accra",
    country: "Ghana",
    countryCode: "GH",
    hours: "8am – 4pm · Mon–Fri",
    verified: "government",
    rating: 3.5,
    reviewCount: 1100,
  },
  {
    id: "gh-court-supreme",
    name: "Supreme Court of Ghana",
    category: "court",
    coordinates: { lat: 5.55, lng: -0.205 },
    address: "High Court Area, Accra",
    city: "Accra",
    region: "Greater Accra",
    country: "Ghana",
    countryCode: "GH",
    verified: "government",
    rating: 4.0,
    reviewCount: 45,
  },
  {
    id: "gh-attraction-independence",
    name: "Independence Square",
    category: "attraction",
    coordinates: { lat: 5.548, lng: -0.192 },
    address: "Black Star Square, Accra",
    city: "Accra",
    region: "Greater Accra",
    country: "Ghana",
    countryCode: "GH",
    rating: 4.5,
    reviewCount: 2800,
    description: "Iconic national square and parade grounds.",
    parking: true,
  },
  {
    id: "gh-park-efua",
    name: "Efua Sutherland Children's Park",
    category: "park",
    coordinates: { lat: 5.57, lng: -0.175 },
    address: "Liberation Road, Accra",
    city: "Accra",
    region: "Greater Accra",
    country: "Ghana",
    countryCode: "GH",
    hours: "8am – 6pm",
    rating: 4.3,
    reviewCount: 640,
    accessibility: true,
  },
  {
    id: "gh-toilet-makola",
    name: "Public Washroom — Makola",
    category: "toilet",
    coordinates: { lat: 5.549, lng: -0.209 },
    address: "Near Makola Market",
    city: "Accra",
    region: "Greater Accra",
    country: "Ghana",
    countryCode: "GH",
    hours: "6am – 7pm",
    rating: 3.2,
    reviewCount: 40,
    accessibility: true,
  },
  {
    id: "gh-ev-airport",
    name: "EV Charger — Airport City",
    category: "ev_charger",
    coordinates: { lat: 5.602, lng: -0.172 },
    address: "Airport City, Accra",
    city: "Accra",
    region: "Greater Accra",
    country: "Ghana",
    countryCode: "GH",
    hours: "24 hours",
    rating: 4.1,
    reviewCount: 22,
    verified: "business",
  },
  {
    id: "gh-hostel-legon",
    name: "University Hostel — Legon",
    category: "hostel",
    coordinates: { lat: 5.648, lng: -0.185 },
    address: "Near UG Legon",
    city: "Accra",
    region: "Greater Accra",
    country: "Ghana",
    countryCode: "GH",
    hours: "Reception 24h",
    rating: 4.0,
    reviewCount: 150,
  },
];

export function getPlaceById(id: string): Place | undefined {
  return PLACES.find((p) => p.id === id);
}

export function searchPlaces(query: string, category?: string): Place[] {
  const q = query.trim().toLowerCase();
  return PLACES.filter((p) => {
    const matchesCategory = !category || category === "all" || p.category === category;
    if (!q) return matchesCategory;
    const hay = `${p.name} ${p.address} ${p.city} ${p.category} ${p.description ?? ""}`.toLowerCase();
    return matchesCategory && hay.includes(q);
  });
}

export function haversineKm(a: { lat: number; lng: number }, b: { lat: number; lng: number }): number {
  const R = 6371;
  const dLat = ((b.lat - a.lat) * Math.PI) / 180;
  const dLng = ((b.lng - a.lng) * Math.PI) / 180;
  const lat1 = (a.lat * Math.PI) / 180;
  const lat2 = (b.lat * Math.PI) / 180;
  const h =
    Math.sin(dLat / 2) ** 2 + Math.cos(lat1) * Math.cos(lat2) * Math.sin(dLng / 2) ** 2;
  return R * 2 * Math.atan2(Math.sqrt(h), Math.sqrt(1 - h));
}

export function nearbyPlaces(
  origin: { lat: number; lng: number },
  category?: string,
  limit = 12,
): (Place & { distanceKm: number })[] {
  return PLACES.map((p) => ({ ...p, distanceKm: haversineKm(origin, p.coordinates) }))
    .filter((p) => !category || category === "all" || p.category === category)
    .sort((a, b) => a.distanceKm - b.distanceKm)
    .slice(0, limit);
}
